const state={config:null,session:null,authMode:'dev',workspaces:[],workspaceId:null,kbs:[],documents:[],chatSessions:[],chatId:null,authTab:'signin'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.style.background=error?'#9f2d2d':'#111827';el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3200)}
function fmtBytes(n){n=Number(n||0);if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(2)} GB`}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function authHeaders(extra={}){const h={...extra};if(state.session?.access_token)h.Authorization=`Bearer ${state.session.access_token}`;return h}
async function refreshSession(){if(state.authMode!=='supabase'||!state.session?.refresh_token)return false;const base=state.config.supabase_url.replace(/\/$/,'');const r=await fetch(`${base}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{'Content-Type':'application/json','apikey':state.config.supabase_publishable_key},body:JSON.stringify({refresh_token:state.session.refresh_token})});if(!r.ok)return false;state.session=await r.json();localStorage.setItem('dq_session',JSON.stringify(state.session));return true}
async function api(path,opts={},retried=false){let res=await fetch(path,{...opts,headers:authHeaders(opts.headers||{})});if(res.status===401&&state.authMode==='supabase'&&!retried&&await refreshSession())return api(path,opts,true);if(res.status===401&&state.authMode==='supabase'){logout(false);throw new Error('Session expired')}if(!res.ok){let msg=`Request failed (${res.status})`;try{const d=await res.json();msg=d.detail||d.message||msg}catch{}throw new Error(msg)}if(res.status===204)return null;return res.json()}
async function init(){state.config=await fetch('/api/public-config').then(r=>r.json());state.authMode=state.config.auth_mode;state.session=JSON.parse(localStorage.getItem('dq_session')||'null');if(state.authMode==='supabase'&&!state.session){showAuth();return}await enterApp()}
function showAuth(){$('#authScreen').classList.remove('hidden');$('#appShell').classList.add('hidden');$('#authHint').textContent='Authentication is provided by your configured Supabase project.'}
async function enterApp(){$('#authScreen').classList.add('hidden');$('#appShell').classList.remove('hidden');$('#userEmail').textContent=state.session?.user?.email || (state.config.auth_mode==='dev'?'dev@docuquery.local':'');await loadWorkspaces()}
async function supabaseAuth(mode,email,password){const base=state.config.supabase_url.replace(/\/$/,'');const url=mode==='signin'?`${base}/auth/v1/token?grant_type=password`:`${base}/auth/v1/signup`;const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','apikey':state.config.supabase_publishable_key},body:JSON.stringify({email,password})});const data=await res.json();if(!res.ok)throw new Error(data.msg||data.message||data.error_description||'Authentication failed');return data}
async function logout(reload=true){if(state.authMode==='supabase'&&state.session?.access_token){try{await fetch(`${state.config.supabase_url.replace(/\/$/,'')}/auth/v1/logout`,{method:'POST',headers:{apikey:state.config.supabase_publishable_key,Authorization:`Bearer ${state.session.access_token}`}})}catch{}}state.session=null;localStorage.removeItem('dq_session');if(reload)location.reload()}

async function loadWorkspaces(){try{state.workspaces=await api('/api/workspaces');if(!state.workspaces.length){showWorkspaceCreate(true);return}renderWorkspaceSelect();if(!state.workspaceId||!state.workspaces.some(w=>w.id===state.workspaceId))state.workspaceId=state.workspaces[0].id;$('#workspaceSelect').value=state.workspaceId;await refreshWorkspace()}catch(e){toast(e.message,true)}}
function renderWorkspaceSelect(){$('#workspaceSelect').innerHTML=state.workspaces.map(w=>`<option value="${w.id}">${esc(w.name)}</option>`).join('')}
async function refreshWorkspace(){if(!state.workspaceId)return;await Promise.all([loadKbs(),loadDocuments(),loadSessions(),loadSettings()]);renderDashboard();if($('#view-activity').classList.contains('active'))loadActivity()}
async function loadKbs(){state.kbs=await api(`/api/knowledge-bases?workspace_id=${state.workspaceId}`);$('#kbList').innerHTML=state.kbs.length?state.kbs.map(k=>`<article class="card"><h4>${esc(k.name)}</h4><p>${esc(k.description||'No description')}</p><small>${k.document_count} document${Number(k.document_count)===1?'':'s'}</small></article>`).join(''):'<div class="empty-state"><b>No knowledge bases yet</b><span>Create one before uploading documents.</span></div>'}
async function loadDocuments(){state.documents=await api(`/api/documents?workspace_id=${state.workspaceId}`);renderDocuments()}
function renderDocuments(){const html=state.documents.length?`<table class="data-table"><thead><tr><th>Document</th><th>Knowledge base</th><th>Status</th><th>Size</th><th></th></tr></thead><tbody>${state.documents.map(d=>`<tr data-document="${d.id}"><td><b>${esc(d.name)}</b><br><small>v${d.version_no||1}</small></td><td>${esc(d.knowledge_base_name)}</td><td><span class="badge ${esc(d.status)}">${esc(d.status||'unknown')}</span></td><td>${fmtBytes(d.file_size)}</td><td><button class="delete-doc" data-id="${d.id}">Archive</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty-state"><b>No documents</b><span>Upload your first PDF, DOCX or TXT file.</span></div>';$('#documentsTable').innerHTML=html;$('#recentDocuments').innerHTML=html;$$('.delete-doc').forEach(b=>b.onclick=()=>archiveDocument(b.dataset.id));startPollingProcessing()}
let pollTimer=null;function startPollingProcessing(){clearTimeout(pollTimer);if(!state.documents.some(d=>!['ready','failed'].includes(d.status)))return;pollTimer=setTimeout(async()=>{await loadDocuments();renderDashboard()},3000)}
async function loadSessions(){state.chatSessions=await api(`/api/chat/sessions?workspace_id=${state.workspaceId}`);$('#chatSessions').innerHTML=state.chatSessions.length?state.chatSessions.map(s=>`<div class="session ${s.id===state.chatId?'active':''}" data-session="${s.id}"><b>${esc(s.title||'Chat')}</b><small>${s.message_count} messages</small></div>`).join(''):'<div class="empty-state"><span>No chats yet.</span></div>';$$('.session').forEach(el=>el.onclick=()=>openSession(el.dataset.session))}
async function loadSettings(){const data=await api(`/api/settings?workspace_id=${state.workspaceId}`);state.settings=data;$('#geminiStatus').textContent=data.provider_credential?`Workspace key configured (${data.provider_credential.key_hint})`:data.managed_gemini_configured?'Using managed DocuQuery Gemini key':'No Gemini key configured';const u=data.usage;$('#usageSettings').innerHTML=`<p><b>Plan:</b> ${esc(u.plan)}</p><p><b>Questions:</b> ${u.questions_used} / ${u.monthly_question_limit}</p><p><b>Storage:</b> ${fmtBytes(u.storage_used)} / ${fmtBytes(u.storage_limit_bytes)}</p>`}
function renderDashboard(){const u=state.settings?.usage||{};$('#metricKb').textContent=state.kbs.length;$('#metricDocs').textContent=state.documents.length;$('#metricQuestions').textContent=u.questions_used||0;$('#metricQuestionLimit').textContent=`of ${u.monthly_question_limit||'—'}`;$('#metricStorage').textContent=fmtBytes(u.storage_used||0);$('#metricStorageLimit').textContent=`of ${fmtBytes(u.storage_limit_bytes||0)}`}

function showWorkspaceCreate(required=false){openModal('Create workspace',`<label>Workspace name<input id="modalWorkspaceName" placeholder="Acme Corporation" autofocus></label><button id="modalCreateWorkspace" class="primary">Create workspace</button>`,()=>{$('#modalCreateWorkspace').onclick=async e=>{e.preventDefault();try{await api('/api/workspaces',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#modalWorkspaceName').value})});$('#modal').close();await loadWorkspaces();toast('Workspace created')}catch(err){toast(err.message,true)}}});if(required)$('#modal').addEventListener('cancel',e=>e.preventDefault(),{once:true})}
function openModal(title,body,onopen){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').showModal();onopen?.()}
function showKbCreate(){openModal('New knowledge base',`<label>Name<input id="modalKbName" placeholder="Credit Policies"></label><label>Description<textarea id="modalKbDesc" placeholder="What belongs in this knowledge base?"></textarea></label><button id="modalCreateKb" class="primary">Create</button>`,()=>{$('#modalCreateKb').onclick=async e=>{e.preventDefault();try{await api('/api/knowledge-bases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:state.workspaceId,name:$('#modalKbName').value,description:$('#modalKbDesc').value||null})});$('#modal').close();await loadKbs();renderDashboard();toast('Knowledge base created')}catch(err){toast(err.message,true)}}})}
function showUpload(){if(!state.kbs.length){toast('Create a knowledge base first',true);return}openModal('Upload document',`<label>Knowledge base<select id="modalUploadKb">${state.kbs.map(k=>`<option value="${k.id}">${esc(k.name)}</option>`).join('')}</select></label><label>Document<input id="modalFile" type="file" accept=".pdf,.docx,.txt" required></label><p class="muted">Maximum ${state.config.max_upload_mb} MB. Files are validated before processing.</p><button id="modalDoUpload" class="primary">Upload & process</button>`,()=>{$('#modalDoUpload').onclick=async e=>{e.preventDefault();const f=$('#modalFile').files[0];if(!f){toast('Choose a file',true);return}const fd=new FormData();fd.append('workspace_id',state.workspaceId);fd.append('knowledge_base_id',$('#modalUploadKb').value);fd.append('file',f);try{await api('/api/documents/upload',{method:'POST',body:fd});$('#modal').close();await loadDocuments();toast('Document queued for processing')}catch(err){toast(err.message,true)}}})}
async function archiveDocument(id){if(!confirm('Archive this document?'))return;try{await api(`/api/documents/${id}`,{method:'DELETE'});await loadDocuments();await loadSettings();renderDashboard();toast('Document archived')}catch(e){toast(e.message,true)}}

function showSourceChooser(){openModal('Choose answer sources',`<p class="muted">Select knowledge bases. With no selection, the chat searches the whole workspace.</p><div class="cards">${state.kbs.map(k=>`<label class="card"><span><input class="source-kb" type="checkbox" value="${k.id}" style="width:auto"> <b>${esc(k.name)}</b></span><small>${k.document_count} documents</small></label>`).join('')}</div><label>Chat title<input id="sourceChatTitle" value="Document Q&A"></label><button id="createScopedChat" class="primary">Start chat</button>`,()=>{$('#createScopedChat').onclick=async e=>{e.preventDefault();const ids=$$('.source-kb:checked').map(x=>x.value);try{const out=await api('/api/chat/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:state.workspaceId,title:$('#sourceChatTitle').value||'Document Q&A',knowledge_base_ids:ids,document_ids:[]})});state.chatId=out.id;$('#modal').close();await loadSessions();await openSession(out.id);toast('Chat ready')}catch(err){toast(err.message,true)}}})}
async function openSession(id){state.chatId=id;await loadSessions();const data=await api(`/api/chat/sessions/${id}`);$('#chatTitle').textContent=data.session.title||'Chat';$('#chatScope').textContent=data.sources.length?`${data.sources.length} selected source${data.sources.length===1?'':'s'}`:'Entire workspace';renderMessages(data.messages)}
function renderMessages(messages){const box=$('#messages');box.innerHTML=messages.length?'':`<div class="empty-state"><b>Ask only what your documents can prove.</b><span>Answers are generated from retrieved evidence and carry source links.</span></div>`;messages.forEach(m=>appendMessage(m.role,m.content,m.citations||[])) ;box.scrollTop=box.scrollHeight}
function appendMessage(role,text,citations=[]){const box=$('#messages');const empty=box.querySelector('.empty-state');if(empty)empty.remove();const el=document.createElement('div');el.className=`message ${role}`;const body=document.createElement('div');body.textContent=text;el.appendChild(body);if(citations.length&&role==='assistant'){const wrap=document.createElement('div');wrap.className='citations';citations.forEach((c,i)=>{const b=document.createElement('button');b.className='citation';b.textContent=`[${i+1}] ${c.document}${c.page?` · p.${c.page}`:c.section?` · ${c.section}`:''}`;b.onclick=()=>openCitation(c);wrap.appendChild(b)});el.appendChild(wrap)}box.appendChild(el);box.scrollTop=box.scrollHeight;return {el,body}}
async function askQuestion(question){if(state.authMode==='supabase')await refreshSession();if(!state.chatId){toast('Start a chat and choose sources first',true);showSourceChooser();return}appendMessage('user',question);const assistant=appendMessage('assistant','');try{const res=await fetch(`/api/chat/sessions/${state.chatId}/ask`,{method:'POST',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify({question})});if(!res.ok){let m='Question failed';try{m=(await res.json()).detail||m}catch{}throw new Error(m)}const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()||'';for(const ev of events){const line=ev.split('\n').find(x=>x.startsWith('data: '));if(!line)continue;const data=JSON.parse(line.slice(6));if(data.type==='token'){assistant.body.textContent+=data.text;$('#messages').scrollTop=$('#messages').scrollHeight}else if(data.type==='citations'&&data.items?.length){const wrap=document.createElement('div');wrap.className='citations';data.items.forEach((c,i)=>{const b=document.createElement('button');b.className='citation';b.textContent=`[${i+1}] ${c.document}${c.page?` · p.${c.page}`:c.section?` · ${c.section}`:''}`;b.onclick=()=>openCitation(c);wrap.appendChild(b)});assistant.el.appendChild(wrap)}else if(data.type==='error')throw new Error(data.message)}}await loadSettings();renderDashboard();await loadSessions()}catch(e){assistant.body.textContent=`Error: ${e.message}`;toast(e.message,true)}}
async function openCitation(c){try{const d=await api(`/api/documents/${c.document_id}/chunks/${c.chunk_id}`);$('#sourceContent').innerHTML=`<h3>${esc(d.name)}</h3><p class="muted">Version ${d.version_no}${d.page_number?` · Page ${d.page_number}`:''}${d.section_title?` · ${esc(d.section_title)}`:''}</p><pre>${esc(d.content)}</pre>`;$('#sourcePanel').classList.remove('hidden')}catch(e){toast(e.message,true)}}

async function loadActivity(){try{const rows=await api(`/api/activity?workspace_id=${state.workspaceId}`);$('#activityTable').innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Resource</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${new Date(r.created_at).toLocaleString()}</td><td>${esc(r.actor_email||'system')}</td><td>${esc(r.action)}</td><td>${esc(r.resource_type||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state"><span>No activity yet.</span></div>'}catch(e){toast(e.message,true)}}
async function loadMembers(){const rows=await api(`/api/workspaces/${state.workspaceId}/members`);$('#memberTable').innerHTML=`<table class="data-table"><thead><tr><th>User</th><th>Role</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.email||r.user_id)}</td><td>${esc(r.role)}</td><td>${esc(r.status)}</td></tr>`).join('')}</tbody></table>`}
function switchView(view){$$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${view}`).classList.add('active');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#viewTitle').textContent=view[0].toUpperCase()+view.slice(1);$('#eyebrow').textContent=view==='dashboard'?'OVERVIEW':'DOCUQUERY';if(view==='activity')loadActivity();if(view==='settings')loadMembers()}

$('#authForm').onsubmit=async e=>{e.preventDefault();try{const data=await supabaseAuth(state.authTab,$('#authEmail').value,$('#authPassword').value);if(state.authTab==='signup'&&!data.access_token){toast('Account created. Confirm your email before signing in.');state.authTab='signin';return}state.session=data;localStorage.setItem('dq_session',JSON.stringify(data));await enterApp()}catch(err){toast(err.message,true)}};
$$('[data-auth-tab]').forEach(b=>b.onclick=()=>{state.authTab=b.dataset.authTab;$$('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#authSubmit').textContent=state.authTab==='signin'?'Sign in':'Create account'});
$('#signOutBtn').onclick=()=>logout();$('#workspaceSelect').onchange=async e=>{state.workspaceId=e.target.value;state.chatId=null;await refreshWorkspace()};$('#newWorkspaceBtn').onclick=()=>showWorkspaceCreate();$('#newKbBtn').onclick=showKbCreate;$('#uploadBtn').onclick=showUpload;$('#dashboardUploadBtn').onclick=()=>{switchView('knowledge');showUpload()};$('#newChatBtn').onclick=showSourceChooser;$('#chooseSourcesBtn').onclick=showSourceChooser;$('#closeSourceBtn').onclick=()=>$('#sourcePanel').classList.add('hidden');$('#refreshActivityBtn').onclick=loadActivity;$$('#nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#askForm').onsubmit=async e=>{e.preventDefault();const q=$('#questionInput').value.trim();if(!q)return;$('#questionInput').value='';await askQuestion(q)};
$('#credentialForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/settings/credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:state.workspaceId,provider:'gemini',secret:$('#geminiKey').value})});$('#geminiKey').value='';await loadSettings();toast('Gemini key encrypted and saved')}catch(err){toast(err.message,true)}};
$('#memberForm').onsubmit=async e=>{e.preventDefault();try{await api(`/api/workspaces/${state.workspaceId}/members/by-email`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#memberEmail').value.trim(),role:$('#memberRole').value})});$('#memberEmail').value='';await loadMembers();toast('Member updated')}catch(err){toast(err.message,true)}};
init().catch(e=>{console.error(e);toast(e.message,true)});