from typing import Protocol, AsyncIterator
class EmbeddingProvider(Protocol):
    async def embed(self,text:str)->list[float]: ...
class LLMProvider(Protocol):
    async def stream_answer(self,question:str,context:str)->AsyncIterator[str]: ...
